version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/workspace
    environment:
      - DATABASE_URL=pgsql://postgres:12345678@db:5432/dbapp
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: dbapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
